### ISSUE TITLE
Please add a license and rename the repo

### ISSUE THREAD

**Issue by unixorn** [Flower7C3/oh-flowers-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

Also, please rename the repo to something less generic that `oh-my-zsh-theme` to make it distinctive in the list, thanks!

**Comment by Flower7C3** [comment]
@unixorn Thank you for your interest. I'm still working on this template. I will take note of your remarks when finalizing the work.

**Comment by Flower7C3** [comment]
@unixorn I belive it is now fixed.

**Comment by unixorn** [comment]
Thanks! Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/681
